#!/bin/bash

# You will need to compile https://github.com/RazrFalcon/svgcleaner (Rust program) and place the binary in your path

rm -rf opt
mkdir -p opt

for svg in $(ls svg/*.svg)
do
	echo "Processing ${svg}"
	svgcleaner ${svg} opt/${svg##*/}
	echo
done
